repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-yaml
    -   id: check-json
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
#-   repo: https://github.com/PyCQA/flake8
#    rev: "4.0.1"
#    hooks:
#    -   id: flake8
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 'v1.5.7'  # Use the sha / tag you want to point at
    hooks:
    -   id: autopep8
#-   repo: https://github.com/psf/black
#    rev: 21.9b0
#    hooks:
#    -   id: black
-   repo: https://github.com/PyCQA/isort
    rev: "5.9.3"
    hooks:
    -   id: isort
#-   repo: https://github.com/PyCQA/pylint
#    rev: "v2.11.1"
#    hooks:
#    -   id: pylint
